// Command ensure-products is the single, global step that establishes the
// Stripe price catalog and publishes the resolved price IDs to D1 for the edge.
//
// The catalog is a GLOBAL concern — one Stripe account, the same metered Prices
// for every cell — so it must be established once, not by all 40 cells racing
// on every startup. This runs EnsureProducts (idempotent: creates/verifies the
// Stripe meters + Prices) and emits `billing_prices` upsert SQL on stdout. Pipe
// it into the appropriate D1:
//
//	STRIPE_SECRET_KEY=sk_live_... go run ./cmd/ensure-products > /tmp/catalog.sql
//	wrangler d1 execute opencomputer-prod --remote --file /tmp/catalog.sql
//
// Run it once per deploy / pricing change (i.e. whenever a TierPriceKey is
// bumped in internal/billing/pricing.go) — not on cell startup.
package main

import (
	"fmt"
	"os"
	"sort"
	"time"

	"github.com/opensandbox/opensandbox/internal/billing"
	"github.com/opensandbox/opensandbox/internal/config"
)

func main() {
	// Load STRIPE_SECRET_KEY from the cloud vault when a trigger is set
	// (SECRETS_VAULT_NAME → Azure Key Vault, OPENSANDBOX_SECRETS_ARN → AWS),
	// exactly as cmd/server does — so this runs anywhere a CP can. No-op if
	// neither trigger is set (then STRIPE_SECRET_KEY must be in the env).
	_ = config.LoadSecretsFromKeyVault()
	_ = config.LoadSecretsFromSecretsManager()

	secret := os.Getenv("STRIPE_SECRET_KEY")
	if secret == "" {
		fmt.Fprintln(os.Stderr, "ensure-products: STRIPE_SECRET_KEY not set (env or vault)")
		os.Exit(1)
	}

	sc := billing.NewStripeClient(secret, "", "", "")
	if err := sc.EnsureProducts(); err != nil {
		fmt.Fprintf(os.Stderr, "ensure-products: EnsureProducts failed: %v\n", err)
		os.Exit(1)
	}

	// Resolved catalog → (key, price_id). Mirrors exactly the line items
	// CreateSubscription attaches: every per-tier compute price plus the flat
	// overage / reserved / disk-overage prices.
	type row struct{ key, priceID string }
	var rows []row
	tiers := make([]int, 0, len(sc.PriceIDs))
	for mb := range sc.PriceIDs {
		tiers = append(tiers, mb)
	}
	sort.Ints(tiers)
	for _, mb := range tiers {
		rows = append(rows, row{fmt.Sprintf("tier_%d", mb), sc.PriceIDs[mb]})
	}
	if sc.OveragePriceID != "" {
		rows = append(rows, row{"overage", sc.OveragePriceID})
	}
	if sc.ReservedPriceID != "" {
		rows = append(rows, row{"reserved", sc.ReservedPriceID})
	}
	if sc.DiskOveragePriceID != "" {
		rows = append(rows, row{"disk_overage", sc.DiskOveragePriceID})
	}
	if len(rows) == 0 {
		fmt.Fprintln(os.Stderr, "ensure-products: no prices resolved — refusing to emit empty catalog")
		os.Exit(1)
	}

	ts := time.Now().Unix()
	fmt.Println("-- Stripe price catalog for the edge — generated by cmd/ensure-products.")
	fmt.Println("-- Idempotent: re-running upserts the current price IDs.")
	for _, r := range rows {
		fmt.Printf(
			"INSERT INTO billing_prices (key, price_id, updated_at) VALUES ('%s','%s',%d) "+
				"ON CONFLICT(key) DO UPDATE SET price_id=excluded.price_id, updated_at=excluded.updated_at;\n",
			r.key, r.priceID, ts,
		)
	}
	fmt.Fprintf(os.Stderr, "ensure-products: emitted %d price rows\n", len(rows))
}
